google_analytics: 
baseurl: /github-actions-catalog
title: GitHub Actions Catalog
description: |
   A collection of GitHub Actions.
copyright: mivano 
url: ""


plugins:
  - "jekyll-seo-tag"

exclude: [
  styles/index.css,
  styles/syntax.css,
  package.json,
  package-lock.json,
  postcss.config.js,
  collect.sh,
  readme.md,
]

collections:
  actions:
    output: true
    sort_by: name
    permalink: /:collection/:name

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      type: actions
    values:
      toc: true
      no_toc: true
      layout: "action"
      comments: true
